### ISSUE TITLE
[Feature Request] Ability to easily move apps in and out of folders.

### ISSUE THREAD

**Issue by i2sage** [P-Connor/plasma-drawer#64] opened 2024-04-13 06:33 UTC
**Is your feature request related to a problem? Please describe.**
By default this widget follows Kde's default grouping of apps and shows them in folder and needs to be manually rearranged in menu edit. idk why its this way but it totally defeats the purpose of having a full screen application launcher (imo).

**Describe the solution you'd like**
Add an option to automatically move apps out of a folder when the folder is deleted, similar to Android.
![photo_6113717252881759498_y](https://github.com/P-Connor/plasma-drawer/assets/137275372/c9a77769-2fae-42fa-b6f2-49b0c66b9605)
or , Implement a drag-and-drop functionality to allow users to easily move apps out of folders.

**Describe alternatives you've considered**
An alternative will be to make the app launcher similar to gnome (40+) by default, where all apps are not in folders by default and can be easily grouped/ungroup by simple drag and drop. 

Thanks.

**Comment by P-Connor** [comment] 2024-04-23 05:23
I hear ya, I think it's pretty clunky using KMenuEdit to rearrange the apps too. I'm hoping to eventually get around to this in the future, but it will most likely require a complete rewrite of the widget, so would take time.

Closing as a duplicate of https://github.com/P-Connor/plasma-drawer/issues/40.

**Closed by P-Connor** 2024-04-23 05:23 UTC
Labels: type:enhancement
