### ISSUE TITLE
[Feature Request]  Better Touch Screen Experience

### ISSUE THREAD

**Issue by shawnk0723** [P-Connor/plasma-drawer#45] opened 2023-01-25 02:39 UTC
Thank you so much for making this cool app. I thought it would be even more perfect if it has a touch screen capability like Launchpad Plasma (https://store.kde.org/p/1364064) that I used to use before I switched to plasma-drawer. Your last update gives even better experience with a new scroll bar. However, it isn't as convenient as launchpad plasma scrolling for touch screen since it doesn't allow scrolling through the menu without using scroll bar at the moment. Other than this, everything is perfect. Thank you. :)

**Comment by P-Connor** [comment] 2023-01-26 22:27
Thanks for the feedback! Marking this as duplicate of #36, feature should be out soon

**Comment by P-Connor** [comment] 2023-02-06 02:53
Touch scrolling should be fixed by a6eb653597fc40abc0680f1f651702021c39b8f3 and in the latest release

**Closed by P-Connor** 2023-02-06 02:53 UTC
Labels: duplicate, status: confirmed
