### ISSUE TITLE
[Bug] Launcher icon is larger than task manager application icons

### ISSUE THREAD

**Issue by stephanlamoureux** [P-Connor/plasma-drawer#54] opened 2023-08-09 23:26 UTC
**Is your feature request related to a problem? Please describe.**
Launcher Icon is larger than the app icons no matter which icon theme I choose.

**Describe the solution you'd like**
Ability to change the launcher icon size.

**Describe alternatives you've considered**
I have tried many other icon themes.

**Additional context**

![Screenshot_20230809_192539](https://github.com/P-Connor/plasma-drawer/assets/16889593/2baae4c4-19e1-4e74-9ea0-8a088a0bf36f)

**Comment by P-Connor** [comment] 2023-08-14 00:42
Hmm, I haven't seen that issue before, and I am unable to recreate it. Could you provide a bit more context? Please fill out the following information below (can be found in KInfoCenter).

- Distro: [e.g. KDE Neon]
- KDE Version: [e.g. 5.24.7]
- KDE Frameworks Version: [e.g. 5.92.0]
- Qt Version: [e.g. 5.15.3]
- Kernel Version: [e.g. 5.15.0-58-generic]
- Graphics Platform: [e.g. X11, Wayland]
- Device Type (if relevant): [e.g. Desktop, Tablet, Steam Deck]

Also, is that the default Icons-Only Task manager? What icon packs have you seen the issue in, and what's the name of the  icon that you are assigning to the widget?

Thanks

**Comment by P-Connor** [comment] 2024-01-28 00:54
Without additional info I've been unable to reproduce the bug. I'm going to close this issue but please comment if you can provide additional context on your system details and I'll re-open

**Closed** 2024-01-28 00:54 UTC
Labels: type:bug
