### ISSUE TITLE
[Feature Request] Favorites

### ISSUE THREAD

**Issue by waffleboi9000** [P-Connor/plasma-drawer#22] opened 2023-01-16 19:25 UTC
It would be useful to designate apps as favorites, which appear outside folders, as well as in their relevant folders, so that they can be quickly selected without having to enter a category folder first. It would also be useful to have an optional favorites folder.

**Comment by P-Connor** [comment] 2023-01-19 07:36
Thanks for the suggestion! The functionality you describe is already possible with kmenuedit (the "Edit Applications" menu). One can add, copy, or move entries to the root page, or to a designated custom "Favorites" category if they would like. I may consider in the future adding a separate area for favorited applications that is not in the main applications grid, but for now I consider it to be not necessary. 

I believe the more important issue is the accessibility of rearranging apps and folders in general, rather than just for one specific use case (favorites). It may not be easy for users to realize that the functionality that you described is possible, or they may just find it tedious. As a result, I plan to target the general rearranging of apps in the future instead. However, let me know if you disagree, and still feel that a favorites system would be worth it.

**Comment by cipricus** [comment] 2023-01-19 10:40
A favorites page, not just a folder is most necessary if one doesn't use the mouse/touch etc but just keys. I do use the touchpad myself, but not for launching apps.

I practically never look for an application in its categories with the mouse, because normally I know its name and typing that is so much easier. 

A request should be: add an option in settings to start the menu with just the favorite applications.

Love the fact that this widget can search files and folders. All good ones do, I hate those that don't. But my second "must" is a favs page when I click Super to open the menu.

**Comment by P-Connor** [comment] 2023-01-19 19:40
From what I understand, you wish to have certain shortcuts available on the first page upon opening the launcher, rather than having to enter any category. Is the following video not achieving what you describe?

https://user-images.githubusercontent.com/45181215/213535081-7d7152c4-d03b-4d46-a06f-3aee8fae9c16.mp4

(Apologies for the low quality and video pace, GitHub only allows up to 10MB files :D)

With the functionality shown in the video already present, I feel that adding a favorites system might only add confusion. If the user already has set up their applications like in the video, and then they choose to favorite an app already on the first page, what is the expected behavior? Should the first page not change? Should there be a duplicate entry at the top of the page? Or should all apps on the first page already be considered favorited, even if they were just moved there in the Edit Applications menu? In that case, if they unfavorite an app that they have moved there, the app would no longer be present in the original folder that they moved it from.

**Comment by P-Connor** [comment] 2023-01-19 19:40
I feel that maybe an "Add to home page" right click option could be more understandable than a favorites system and fulfill all use cases. It would only be visible for apps not already on the "home page" (i.e. the first page you see on opening the launcher), and would just add an additional entry to the first page.

**Comment by cipricus** [comment] 2023-01-19 20:20
I find this idea interesting. New to me, but I will try it. Home page solution is fine.

**Comment by cipricus** [comment] 2023-01-19 20:26
> an "Add to home page" right click option could be more understandable

That will be much easier than drag-drop as seen in video. And maybe it should copy to "home" instead of move?

**Comment by cipricus** [comment] 2023-01-20 13:29
I certainly like this new approach, as I have just tested it.  But editing the applications list as such is not that easy as working withing the widget to get a grid of preferred applications, and there is also the problem that we change the list of applications for all possible widgets, while the applications editor has just a "restore to system menu" option, but not a way of saving  a certain configuration. 

On the other hand, I like this approach as it gives more control to the user, not to mention the fact that the favorites grid doesn't usually allow the order of the favorites to be changed, and when it does the changes are not permanent etc

**Comment by cipricus** [comment] 2023-01-20 20:49
After a while I can confirm that after putting all application categories in a top-category called "All" and left only my preferred apps at top-level, while this works fine with this widget, with others, including the default,  the different categories under "All" are not accessible anymore.

**Comment by P-Connor** [comment] 2023-01-20 21:02
> But editing the applications list as such to get a grid of preferred applications is not as easy as within the widget, and there is also the problem that we change the list of applications for all possible widgets, while the applications editor has just a "restore to system menu" option, but not a way of saving a certain configuration.

I absolutely agree, I’m not the biggest fan of kmenuedit, and I also wish you could edit the menus on a per-launcher basis or save certain configurations. I chose to use the default kicker backend (the backend that the default applications menu and dashboard use) for now, which came with some limitations (lack of ability to rearrange apps or make folders from the plasmoid) but was much easier to implement and was already well tested. Ideally, it would be best to write a custom backend in C++ that can handle drag and drop to add folders or rearrange shortcuts, but then I believe it would not be possible for the widget to be easily downloadable from the widget browser as it would have to be compiled. However, it would be possible to write a custom model in QML that only uses the default kicker backend for initialization on installation and then stores it’s arrangement in the widget’s config. This would allow modification of the application arrangement just for plasma drawer, and would allow me to set up editing the arrangement from within the launcher itself (via drag and drop, right click actions, an “edit mode”, etc.). This is my plan for the future (see #40), but it will take some time to implement and is a lower priority than some of the other issues.

**Comment by P-Connor** [comment] 2023-01-20 21:08
I’m gonna mark this as wontfix for now, as the real issue is rearranging apps in general

**Closed by P-Connor** 2023-01-20 21:08 UTC
Labels: type:enhancement, status:wontfix
