### ISSUE TITLE
Be able to move apps icons outside the directories like Gnome.

### ISSUE THREAD

**Issue by Tuxman2** [P-Connor/plasma-drawer#61] opened 2024-02-26 13:47 UTC
Hello,

it will be great if we can move apps outside the directories in the grid like Gnome. So, we can only display apps (icons) on the grid.

Thanks.

**Comment by P-Connor** [comment] 2024-03-08 08:00
Hi, if you wish to display apps outside of any directory you can do so, it’s just a bit hard to discover. Simply drag the app outside of any folder in kmenuedit, as shown in [this comment](https://github.com/P-Connor/plasma-drawer/issues/22#issuecomment-1397506304).

It’s not perfect though, so I’m planning on eventually adding the ability to rearrange the apps within the widget itself (see #40)

**Comment by Tuxman2** [comment] 2024-03-09 12:00
OK. 

Is plasma-drawer working well with touchscreen ? Can it be similar like the grid in Gnome when it is used with touchscreen ?

Regards.

**Comment by P-Connor** [comment] 2024-03-15 02:39
Yes, other users have reported that it works well with touchscreen! However, I personally don’t own a touchscreen device to thoroughly test it on, so try it out and open another issue if you discover any problems.

**Comment by P-Connor** [comment] 2024-03-15 02:39
Going to close this issue as it’s a bit of a duplicate of #40

**Closed by P-Connor** 2024-03-15 02:39 UTC
Labels: type:enhancement
