### ISSUE TITLE
Feature Request: Add right-click menu on search results

### ISSUE THREAD

**Issue by fwmm01** [P-Connor/plasma-drawer#24] opened 2023-01-17 11:02 UTC
When right-clicking an app, there are several options including, "add to Desktop" and "Add to panel".
However, when searching for an app, you cannot get the context menu from right-clicking on the result.

**Comment by P-Connor** [comment] 2023-02-01 03:23
Duplicate of #43
(You actually posted yours first but yeah)

**Comment by P-Connor** [comment] 2023-02-06 02:56
Fixed by 43851ecbb4a8ccf9b200c82ee26e55f0276cf147

**Closed by P-Connor** 2023-02-06 02:56 UTC
Labels: duplicate, status: confirmed
